### PR TITLE
New data format, deps

### PR DESCRIPTION
**Pull request by gwm17**
This is a working draft targeting the next release of the merger. So far this addresses two key issues we want solved for the merger:

- Issue #44 : The format before didn't take advantage of standard HDF5 metadata attributes. We've now leveraged that to make the files much easier to parse. 
- Issue #60 : hdf5-rust as we used it before was more or less unmaintained. We've now switched to the active fork.

### CODE REVIEW

**Comment by gwm17** [comment]
Added in the work for Issue #66

**Comment by gwm17** [comment]
Added in the work for #65

**Comment by gwm17** [comment]
Added unit testing for PadMap, as per #67 
Unfortunately the rest of the code would basically require a fake AT-TPC dataset, which is pretty complicated to setup. For now this will be our only test, but we should try to figure out how to get more.

**Comment by DBazin** [comment]
Hi Gordon,

other than making sure the scalers group is separate from the events group (right now it looks like it is inside), everything looks good.

Cheers,
Daniel

On Sep 19, 2024, at 12:23 PM, Gordon McCann ***@***.***> wrote:

[EXTERNAL] This email originated from outside of FRIB



@gwm17<https://github.com/gwm17> requested your review on: #64<https://github.com/ATTPC/attpc_merger/pull/64> New data format, deps.

**Comment by gwm17** [comment]
@DBazin , thanks! I just double checked the code and the scalers are *not* inside the event group, as it should be. I'll update the README to make sure everything is clear!

**Pull request merged**
